# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openhelpdesk', '0003_organizationsetting_email_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsetting',
            name='email_background_color',
            field=models.CharField(blank=True, default='lightskyblue', max_length=20),
        ),
        migrations.AlterField(
            model_name='organizationsetting',
            name='filter_label',
            field=models.CharField(blank=True, max_length=20, verbose_name='Filter label'),
        ),
    ]
