# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openhelpdesk', '0004_auto_20160426_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='organizations',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='openhelpdesk.OrganizationSetting'),
        ),
    ]
