# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openhelpdesk', '0005_category_organizations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='organizations',
        ),
        migrations.AddField(
            model_name='category',
            name='enable_on_organizations',
            field=models.ManyToManyField(blank=True, related_name='categories_enabled', to='openhelpdesk.OrganizationSetting'),
        ),
        migrations.AddField(
            model_name='tipology',
            name='disable_on_oranizations',
            field=models.ManyToManyField(blank=True, related_name='tipologies_disabled', to='openhelpdesk.OrganizationSetting'),
        ),
        migrations.AddField(
            model_name='tipology',
            name='enable_on_organizations',
            field=models.ManyToManyField(blank=True, related_name='tipologies_enabled', to='openhelpdesk.OrganizationSetting'),
        ),
    ]
