# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openhelpdesk', '0006_auto_20160427_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipology',
            old_name='disable_on_oranizations',
            new_name='disable_on_organizations',
        ),
    ]
