# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-03 16:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openhelpdesk', '0007_auto_20160427_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subteam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('title', models.CharField(max_length=500, unique=True, verbose_name='Title')),
                ('organizations_managed', models.ManyToManyField(blank=True, related_name='managed_from', to='openhelpdesk.OrganizationSetting', verbose_name='organizations managed')),
                ('teammates', models.ManyToManyField(blank=True, related_name='subteams', to=settings.AUTH_USER_MODEL, verbose_name='teammate')),
            ],
            options={
                'verbose_name': 'Subteam',
                'verbose_name_plural': 'subteams',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='TeammateSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('default_subteam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openhelpdesk.Subteam', verbose_name='default subteam')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ohteammate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teammate Setting',
                'verbose_name_plural': 'Teammate Settings',
                'ordering': ('user',),
            },
        ),
    ]
