# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 14:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openhelpdesk', '0008_subteam_teammatesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subteam',
            name='organizations_managed',
            field=models.ManyToManyField(blank=True, null=True, related_name='managed_from', to='openhelpdesk.OrganizationSetting', verbose_name='organizations managed'),
        ),
        migrations.AlterField(
            model_name='subteam',
            name='teammates',
            field=models.ManyToManyField(blank=True, null=True, related_name='subteams', to=settings.AUTH_USER_MODEL, verbose_name='teammate'),
        ),
        migrations.AlterField(
            model_name='teammatesetting',
            name='default_subteam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='openhelpdesk.Subteam', verbose_name='default subteam'),
        ),
    ]
