# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 15:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openhelpdesk', '0009_auto_20160505_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subteam',
            options={'ordering': ('title',), 'verbose_name': 'Subteam', 'verbose_name_plural': 'Subteams'},
        ),
        migrations.RemoveField(
            model_name='tipology',
            name='enable_on_organizations',
        ),
        migrations.AlterField(
            model_name='category',
            name='enable_on_organizations',
            field=models.ManyToManyField(blank=True, related_name='categories_enabled', to='openhelpdesk.OrganizationSetting', verbose_name='Enable on organizations'),
        ),
        migrations.AlterField(
            model_name='subteam',
            name='organizations_managed',
            field=models.ManyToManyField(blank=True, related_name='managed_from', to='openhelpdesk.OrganizationSetting', verbose_name='organizations managed'),
        ),
        migrations.AlterField(
            model_name='subteam',
            name='teammates',
            field=models.ManyToManyField(blank=True, related_name='subteams', to=settings.AUTH_USER_MODEL, verbose_name='teammates'),
        ),
        migrations.AlterField(
            model_name='teammatesetting',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oh_teammate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tipology',
            name='disable_on_organizations',
            field=models.ManyToManyField(blank=True, related_name='tipologies_disabled', to='openhelpdesk.OrganizationSetting', verbose_name='Disable on organizations'),
        ),
    ]
