# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('openhelpdesk', '0010_auto_20160512_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'default_manager_name': 'objects', 'get_latest_by': 'created', 'ordering': ('-created',), 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AddField(
            model_name='subteam',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
